services:
  iroffer:
    build:
      context: .
      args:
        CONT_IMG_VER: ${CONT_IMG_VER}
        IROFFER_USER_ID: ${IROFFER_USER_ID}
        IROFFER_GROUP_ID: ${IROFFER_GROUP_ID}
        IROFFER_URL: ${IROFFER_URL}
        IROFFER_SHA256: ${IROFFER_SHA256}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_CONFIG_DIR}:${IROFFER_CONFIG_DIR}
      - ${HOST_DATA_DIR}:${IROFFER_DATA_DIR}
      - ${HOST_LOG_DIR}:${IROFFER_LOG_DIR}
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}

